[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E","F","I","B","UP"]
ignore = []
exclude = ["venv",".venv","build","dist"]

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["."]
